---
title: "README"
author: "shelley herbrich"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: TRUE
---

# Overview

Most of the existing acute myeloid leukemia (AML) stem cell datasets are comprised of stem cells identified using an array of immunophenotypic definitions, however, we now appreciate that the immunopheotype does not always indicate true stem cell function. At the end of 2016, Ng et al introduced the first functional AML stem cell dataset as a part of their Nature manuscript, “A 17-gene stemness score for rapid determination of risk in acute leukaemia”. While the main conclusions of the manuscript are accurate and reproducible, we believe that there is a simple approach to better understand the biology of these functional AML stem cells. Here, we present an alternative analytical approach that accounts for the variability in cell stemness within a given patient using a multivariate statistical model to significantly expand the biological findings of the original manuscript. 

# Brief Results

* [01_grab_data](results/01_grab_data.md) downloads the 
  raw datasets used from the web.
* [02_process_data](results/02_process_data.md) sets up the data matrix and corresponding annotation dataframes.
* [03_recreate_manuscript_results](results/03_recreate_manuscript_results.md) closely recapitulates the original analysis described in the manuscript. 
* [04_modified_anova_analysis](results/04_modified_anova_analysis.md) presents our modified analysis in which we use an anova model to account for inter-patient variability.
* [05_compare_analyses](results/05_compare_analyses.md) compares the results obtained from the original and modified analyses.


# Running the Analysis

Roughly, our analyses involve running the R and Rmd files
in [R](R) in the order they appear. 

Run [R/95_make_clean.R](R/95_make_clean.R) to clear out any
downstream products.

Run [R/99_make_all.R](R/99_make_all.R) to re-run the analysis 
from beginning to end, including generating this README.

Raw data from the web is stored in [data][data].

Reports and interim results are stored in [results][results].

## Required Libraries

These analyses were performed in RStudio 1.1.414 using 
`r version[["version.string"]]`, 
and use:

* downloader `r packageVersion("downloader")`
* GEOquery   `r packageVersion("GEOquery")`
* here       `r packageVersion("here")`
* readr      `r packageVersion("readr")`
* rmarkdown  `r packageVersion("rmarkdown")`
* illuminaHumanv4.db  `r packageVersion("illuminaHumanv4.db")`
* wesanderson  `r packageVersion("wesanderson")`
* limma  `r packageVersion("limma")`
* ggplot2  `r packageVersion("ggplot2")`
* gridExtra  `r packageVersion("gridExtra")`
* grid  `r packageVersion("grid")`

